name: eslint #произвольно выбранное имя задания

on: push  # on – определяет события, которые запускают воркфлоу

jobs:
  
  test:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - name: checkout
        uses: actions/checkout@v2 # checkout – клонирует репозиторий

      - name: install
        run: make install

      - name: linter
        run: make lint

      - name: run tests
        run: make test

      - name: run test-coverage and publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true